import 'package:flutter/material.dart';

/// The Night Sky world's little spaceship, drawn nose-to-the-right.
///
/// Prefers the illustrated sprite generated by `scripts/generate_spaceship.py`
/// and falls back to a drawn rocket when that asset is missing or unreadable,
/// so a half-finished art drop can never leave a blank where the ship should
/// be. The drawn form points the same way as the sprite (nose right) so callers
/// can rotate either one along a flight path and get the same result.
class Spaceship extends StatelessWidget {
  const Spaceship({
    super.key,
    required this.size,
    this.accent = const Color(0xFFFFD27D),
    this.asset = _defaultAsset,
  });

  final double size;

  /// Fin/nose colour of the drawn fallback. Ignored once the sprite loads.
  final Color accent;

  /// Sprite path, resolved against the shared_ui package.
  final String asset;

  static const _defaultAsset = 'assets/worlds/spaceship.png';

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: size,
      height: size,
      child: Image.asset(
        asset,
        package: 'shared_ui',
        fit: BoxFit.contain,
        filterQuality: FilterQuality.medium,
        errorBuilder: (_, __, ___) =>
            CustomPaint(painter: _RocketPainter(accent: accent)),
      ),
    );
  }
}

/// A simple drawn rocket used until the illustrated ship is generated. Nose to
/// the right, a warm flame trailing left, so it matches the sprite's heading.
class _RocketPainter extends CustomPainter {
  const _RocketPainter({required this.accent});

  final Color accent;

  @override
  void paint(Canvas canvas, Size size) {
    final w = size.width;
    final h = size.height;
    final cy = h / 2;

    // Flame first, so the body sits over its root.
    canvas.drawPath(
      Path()
        ..moveTo(w * 0.30, cy - h * 0.09)
        ..quadraticBezierTo(w * 0.02, cy, w * 0.30, cy + h * 0.09)
        ..close(),
      Paint()..color = const Color(0xFFFFB24D),
    );
    canvas.drawPath(
      Path()
        ..moveTo(w * 0.30, cy - h * 0.05)
        ..quadraticBezierTo(w * 0.14, cy, w * 0.30, cy + h * 0.05)
        ..close(),
      Paint()..color = const Color(0xFFFFE08A),
    );

    // Body: a rounded capsule tapering to a nose on the right.
    canvas.drawPath(
      Path()
        ..moveTo(w * 0.30, cy - h * 0.16)
        ..lineTo(w * 0.66, cy - h * 0.16)
        ..quadraticBezierTo(w * 0.92, cy - h * 0.13, w * 0.94, cy)
        ..quadraticBezierTo(w * 0.92, cy + h * 0.13, w * 0.66, cy + h * 0.16)
        ..lineTo(w * 0.30, cy + h * 0.16)
        ..quadraticBezierTo(w * 0.24, cy, w * 0.30, cy - h * 0.16)
        ..close(),
      Paint()..color = const Color(0xFFECEAF6),
    );

    // Fins.
    final finPaint = Paint()..color = accent;
    canvas.drawPath(
      Path()
        ..moveTo(w * 0.36, cy - h * 0.15)
        ..lineTo(w * 0.30, cy - h * 0.30)
        ..lineTo(w * 0.46, cy - h * 0.15)
        ..close(),
      finPaint,
    );
    canvas.drawPath(
      Path()
        ..moveTo(w * 0.36, cy + h * 0.15)
        ..lineTo(w * 0.30, cy + h * 0.30)
        ..lineTo(w * 0.46, cy + h * 0.15)
        ..close(),
      finPaint,
    );

    // Porthole.
    canvas.drawCircle(
      Offset(w * 0.62, cy),
      h * 0.09,
      Paint()..color = const Color(0xFF6FC4E8),
    );
    canvas.drawCircle(
      Offset(w * 0.62, cy),
      h * 0.09,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = h * 0.02
        ..color = const Color(0xFFECEAF6),
    );
  }

  @override
  bool shouldRepaint(_RocketPainter oldDelegate) => oldDelegate.accent != accent;
}
